import Head from "next/head";
import { Header } from "@/src/components/Header/Header";
import { Posts as PostsComponent } from "@/src/components/Posts";

const Posts = () => {
  return (
    <>
      <Head>
        <title>Posts page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <div className="p-24 mx-auto max-w-[1200px] ">
        <PostsComponent />
      </div>
    </>
  );
};

export default Posts;
