import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.css";
import { Header } from "@/src/components/Header/Header";
import { Posts as PostsComponent } from "@/src/components/Posts";

const inter = Inter({ subsets: ["latin"] });

const Posts = () => {
  return (
    <>
      <Head>
        <title>Posts page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />

      <PostsComponent />
    </>
  );
};

export default Posts;
