import Head from "next/head";
import { Header } from "@/src/components/Header/Header";
import { User } from "@/src/components/User";

const UserId = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div>
          <Header />
        </div>
        <User />
      </main>
    </>
  );
};

export default UserId;
