import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/src/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

const Index = () => {
  return (
    <>
      <Head>
        <title>about page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <h1>Next.jsで学ぶReact講座</h1>
      <p>JSONPlaceholderのAPIを色々叩いてみるよ！</p>
    </>
  );
};

export default Index;
