import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.css";
import { Headline } from "@/src/components/Headline";
import { Header } from "@/src/components/Header/Header";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const PostId = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Headline title="Index page!!">
            <code className={styles.code}>index</code>
          </Headline>
          <Header />
        </div>
        <div>{router.query.id}</div>
      </main>
    </>
  );
};

export default PostId;
