import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Footer } from "../components/Footer";
import { Logo } from "@/components/logo";
import { Headline } from "@/components/Headline";
import { Headerlogo } from "@/components/Headerlogo";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Headline title="Index page!!">
            <code className={styles.code}>index</code>
          </Headline>
          <Header />
          <Headerlogo />
        </div>
        <Logo />

        <Footer />
      </main>
    </>
  );
}
