import Head from "next/head";
import { Header } from "@/src/components/Header/Header";
import { Users as UsersComponent } from "@/src/components/Users";

const Users = () => {
  return (
    <>
      <Head>
        <title>Users page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />

      <UsersComponent />
    </>
  );
};

export default Users;
