import Head from "next/head";
import { Header } from "@/src/components/Header/Header";
import { CommentComponent } from "@/src/components/Comments";

const Comments = () => {
  return (
    <>
      <Head>
        <title>Comments page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <CommentComponent />
    </>
  );
};

export default Comments;
